trade:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: second_trade
    username: root
    password: fuxiao0714.MySQL
  wechat:
    appid: wxec7e564f638e8012
    secret: 3fe6125faf4e3198fb3387c67d963803
  redis:
    host: localhost
    port: 6379
    database: 0
  alioss:
    access-key-id: LTAI5tPuZvchCJDz92LWqQfk
    access-key-secret: v0pLAOTFXeWygiZQb56EaLu4RpwfDx
    bucket-name: myalioss-sw
    endpoint: oss-cn-hangzhou.aliyuncs.com
