server:
  port: 8081

spring:
  redis:
    host: ${trade.redis.host}
    port: ${trade.redis.port}
    database: ${trade.redis.database}
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${trade.datasource.driver-class-name}
      url: jdbc:mysql://${trade.datasource.host}:${trade.datasource.port}/${trade.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${trade.datasource.username}
      password: ${trade.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.trade.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      trade:
        mapper: debug
        service: info
        controller: info

trade:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: itheima
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  wechat:
    appid: ${trade.wechat.appid}
    secret: ${trade.wechat.secret}
  alioss:
    access-key-id: ${trade.alioss.access-key-id}
    endpoint: ${trade.alioss.endpoint}
    access-key-secret: ${trade.alioss.access-key-secret}
    bucket-name: ${trade.alioss.bucket-name}
